version: "3.6"

services:

  api-gateway:
    image: docker.nexus.archi-lab.io/archilab/${POM_ARTIFACTID}:${POM_VERSION}
    ports:
      - "8081:8081"
    restart: always
    networks:
      - prox

networks:
  prox:
    external: true
