version: "3.6"

services:

  api-gateway:
    image: docker.nexus.archi-lab.io/archilab/prox-api-gateway
    ports:
      - "8081:8081"
    restart: always
    networks:
      - prox

networks:
  prox:
    external: true
