eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/
server:
  port: 8081
spring:
  application:
    name: api-gateway
zuul:
  add-host-header: true
  addProxyHeaders: false
  ignored-services: "*"
  routes:
    modules:
      path: /modules/**
      service-id: module-service
      strip-prefix: false
    modules-profile:
      path: /profile/modules/**
      service-id: module-service
      strip-prefix: false
    projectmodules:
      path: /projectModules/**
      service-id: project-service
      strip-prefix: false
    projectmodules-profile:
      path: profile/projectModules/**
      service-id: project-service
      strip-prefix: false
    projects:
      path: /projects/**
      service-id: project-service
      strip-prefix: false
    projects-profile:
      path: /profile/projects/**
      service-id: project-service
      strip-prefix: false
    projectstudycourses:
      path: /projectStudyCourses/**
      service-id: project-service
      strip-prefix: false
    projectstudycourses-profile:
      path: /profile/projectStudyCourses/**
      service-id: project-service
      strip-prefix: false
    studycourses:
      path: /studyCourses/**
      service-id: module-service
      strip-prefix: false
    studycourses-profile:
      path: /profile/studyCourses/**
      service-id: module-service
      strip-prefix: false
    tags:
      path: /tags/**
      service-id: tag-service
      strip-prefix: false
    tagCollections:
      path: /tagCollections/**
      service-id: tag-service
      strip-prefix: false
    tagRecommendations:
      path: /tagRecommendations/**
      service-id: tag-service
      strip-prefix: false
    tags-profile:
      path: /profile/tags/**
      service-id: tag-service
    proposal:
      path: /proposal/**
      service-id: proposal-service
      strip-prefix: false
    proposals:
      path: /proposals/**
      service-id: proposal-service
      strip-prefix: false
    proposals-profile:
      path: /profile/proposals/**
      service-id: proposal-service
      strip-prefix: false
  sensitiveHeaders: Cookie,Set-Cookie
