eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/
server:
  port: 8081
spring:
  application:
    name: api-gateway
zuul:
  add-host-header: true
  addProxyHeaders: false
  ignored-services: "*"
  routes:
    modules:
      path: /modules/**
      service-id: module-service
    modules-profile:
      path: /profile/modules/**
      service-id: module-service
    projectmodules:
      path: /projectModules/**
      service-id: project-service
    projectmodules-profile:
      path: /profile/projectModules/**
      service-id: project-service
    projects:
      path: /projects/**
      service-id: project-service
    projects-profile:
      path: /profile/projects/**
      service-id: project-service
    projectstudycourses:
      path: /projectStudyCourses/**
      service-id: project-service
    projectstudycourses-profile:
      path: /profile/projectStudyCourses/**
      service-id: project-service
    studycourses:
      path: /studyCourses/**
      service-id: module-service
    studycourses-profile:
      path: /profile/studyCourses/**
      service-id: module-service
    search-project:
      path: /search/**
      service-id: search-service
    search-profile:
      path: /profile/search/**
      service-id: search-service
    tags:
      path: /tags/**
      service-id: tag-service
    tags-profile:
      path: /profile/tags/**
      service-id: tag-service
    tagcollections:
      path: /tagCollections/**
      service-id: tag-service
    tagcollections-profile:
      path: /profile/tagCollections/**
      service-id: tag-service
    tagrecommendations:
      path: /tagRecommendations/**
      service-id: tag-service
    tagrecommendations-profile:
      path: /profile/tagRecommendations/**
      service-id: tag-service
    proposals:
      path: /proposals/**
      service-id: proposal-service
    proposals-profile:
      path: /profile/proposals/**
      service-id: proposal-service
  sensitiveHeaders: Cookie,Set-Cookie
  strip-prefix: false
