version: "3.6"

services:

  api-gateway:
    image: docker.nexus.archi-lab.io/archilab/${IMAGE}:${TAG}
    ports:
      - "8081:8081"
    networks:
      - prox

networks:
  prox:
    external: true
